### DISCUSSION TITLE
Clarification on Subscription Process Responses

### DISCUSSION THREAD

**Discussion by sachinvodafone** [camaraproject/DeviceStatus#168] [General]
HI Team , 
I would like to confirm the following:

Scenario 1: When a client creates a subscription for devices, the process is asynchronous. If the client requests the subscription status for all devices and some subscriptions have been completed while others are still in progress, what response will the client receive? Will the response include information only about the completed subscriptions, or will it also indicate that the remaining subscriptions are still being processed (i.e., a partial response showing that processing is ongoing)?

Scenario 2: When a client attempts to retrieve the subscription of specific devices using a “subscription ID” and the subscription has already been deleted or expired, what response can the client expect?

**Comment by maxl2287** [comment]
Responding to your scenarios:

Scenario 1: As of now you cannot create one subscription for multiple devices. You can create a subscription including multiple subscription-`types` to subscribe on for one device.
Based on the current definition, you can as of now just create one subscription on a `type` per request.
Lets imagine we allow the client to subscribe to multiple `types` within one request for a device asynchronously.
The client will receive a subscriptionId as an outcome, while the subscription-creation process is still ongoing.

When the client requests then GET /subscriptions/{subscriptionId}, then you will get the subscription model, including the current status.
The status is described as:

```yaml
        status:
          type: string
          description: |-
            Current status of the subscription - Management of Subscription State engine is not mandatory for now. Note not all statuses may be considered to be implemented. Details:
              - `ACTIVATION_REQUESTED`: Subscription creation (POST) is triggered but subscription creation process is not finished yet.
              - `ACTIVE`: Subscription creation process is completed. Subscription is fully operative.
              - `INACTIVE`: Subscription is temporarily inactive, but its workflow logic is not deleted.
              - `EXPIRED`: Subscription is ended (no longer active). This status applies when subscription is ended due to `SUBSCRIPTION_EXPIRED` or `ACCESS_TOKEN_EXPIRED` event.
              - `DELETED`: Subscription is ended as deleted (no longer active). This status applies when subscription information is kept (i.e. subscription workflow is no longer active but its meta-information is kept).
          enum:
            - ACTIVATION_REQUESTED
            - ACTIVE
            - EXPIRED
            - INACTIVE
            - DELETED
```
In your case the status will be "ACTIVATION_REQUESTED", when not all subscriptions are partial active.
So you may receive already callbacks, but maybe for some `type`-subscriptions not.

Scenario 2: This depends on the provider implementation. It's up to the provider to decide, if it deletes directly the subscription after it was deleted by the user or expired. But in such cases a final `subscription-ends`-event will be send to the `sink` / `webhook`.
If this is already deleted and the clients request for this subscription, then the provider can either: 

a. Response with 404 that the resource is not anymore found
b. The resource is not yet deleted. The provider can respond then with 200 - OK and the `status`: `DELETED` or `EXPIRED`.
