### ISSUE TITLE
Update naming of "EventType"-components and other descriptions

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#142]
**Problem description**
(1) The subscription-components for "EventType" are described by SubscriptionEventType: and SubscriptionCreationEventType.
DeviceLocation renamed it already to SubscriptionEventType (for the creation of a subscription) and NotificationEventType (for CloudEvents).

(2) Also some of the descriptions can be updated to deliver more context and explanation.

### Example
```
subscriptionExpireTime:
          type: string
          format: date-time
          example: 2023-01-17T13:18:23.682Z
          description: The subscription expiration time in date-time format.
```

to 

```
subscriptionExpireTime:
          type: string
          format: date-time
          example: 2023-01-17T13:18:23.682Z
          description: The subscription expiration time in date-time format.
          description: The date time when the status-tracking has to be terminated.
            It must follow [RFC 3339](https://datatracker.ietf.org/doc/html/rfc3339#section-5.6) and must have time zone.
            Recommended format is yyyy-MM-dd'T'HH:mm:ss.SSSZ (i.e. which allows 2023-07-03T14:27:08.312+02:00 or 2023-07-03T12:27:08.312Z
```

**Expected behavior**
Rename:
- SubscriptionCreationEventType to SubscriptionEventType 
- SubscriptionEventType to NotificationEventType
