### ISSUE TITLE
Remove terms of service and contact from APIs

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#182]
**Problem description**
Terms of service and contact are optional per commonalities guidelines. 
Since these are not providing value, we should remove them.

```yaml
  termsOfService: http://swagger.io/terms/
  contact:
    email: project-email@sample.com
```

**Expected behavior**
Remove this for every API.
