### ISSUE TITLE
[Device-Roaming-Subscription]: Protocol components are missing in specification

### ISSUE THREAD

**Issue by maxl2287** [camaraproject/DeviceStatus#207]
**Describe the bug**
The components described in the `descriminator` for the `prototocol`-property are missing.
This causes problems with our code-generator and makes it unpossible to create the expected property-models.

See:
```yaml
      discriminator:
        propertyName: protocol
        mapping:
          HTTP: "#/components/schemas/HTTPSubscriptionRequest"
          MQTT3: "#/components/schemas/MQTTSubscriptionRequest"
          MQTT5: "#/components/schemas/MQTTSubscriptionRequest"
          AMQP: "#/components/schemas/AMQPSubscriptionRequest"
          NATS: "#/components/schemas/NATSSubscriptionRequest"
          KAFKA: "#/components/schemas/ApacheKafkaSubscriptionRequest"
```
Tested with [r1.2 - device-roaming-status-subscriptions.yaml](https://github.com/camaraproject/DeviceStatus/blob/r1.2/code/API_definitions/device-roaming-status-subscriptions.yaml)
**Expected behavior**
The components should be there, otherwise the yaml is invalid.
