### ISSUE TITLE
[Device-Roaming-Subscription]: The example for a sub - initialEvent and error is wrong

### ISSUE THREAD

**Issue by dfischer-tech** [camaraproject/DeviceStatus#209]
**Problem description**
The example for a sub - initialEvent is wrong - it shows a reachability example
```
initialEvent:
  type: boolean
  description: |
     Set to `true` by API consumer if consumer wants to get an event as soon as the subscription is created and current situation reflects event request.
     Example: Consumer subscribes to reachability SMS. If consumer sets initialEvent to true and device is already reachable by SMS, an event is triggered.
```

**Expected behavior**
Corrected version
```
initialEvent:
  type: boolean
  description: |
     Set to `true` by API consumer if consumer wants to get an event as soon as the subscription is created and current situation reflects event request.
     Example: Consumer subscribes to roaming-on. If consumer sets initialEvent to true and the device is already roaming-on, an event is triggered.
```
and...
The example for CreateSubscriptionUnprocessableEntity422 - MultieventSubscriptionNotSupported instead of PermissionDenied.
```
MultieventSubscriptionNotSupported:
  value:
    status: 422
      code: MULTIEVENT_SUBSCRIPTION_NOT_SUPPORTED
      message: Multi event types subscription not managed
```
BTW: same 2nd issue in [Device Reachability Status Subscriptions]
